### ISSUE TITLE
Amalgamation Link Down

### ISSUE THREAD

**Issue by hoffmabc** [leapcode/pysqlcipher#16]
http://futeisha.org/sqlcipher/amalgamation-sqlcipher-2.1.0.zip

is no longer alive. What gives?

**Comment by kalikaneko** [comment]
I think you're using an old release, or an old repo snapshot.
The correct url now is
``` 
amalgamation_url = ("https://downloads.leap.se/libs/pysqlcipher/"
                        "amalgamation-sqlcipher-2.1.0.zip")
```

Besides, the next release will not rely on the amalgamation download, so if you're depending on it better compile it against system libs.

**Comment by hoffmabc** [comment]
We are getting the error when installing via pip. It seems right on pypi though...hmmm.

**Comment by kalikaneko** [comment]
hmm maybe you were using local caches?
