### ISSUE TITLE
Please remove an amalgamation download, and link to sqlcipher shared library instead

### ISSUE THREAD

**Issue by yurivict** [leapcode/pysqlcipher#21]
It is easier for packagers this way. There should be no benefit in downloading and compiling amalgamation vs. linking to the shared library.

**Comment by kalikaneko** [comment]
I have pushed version 2.6.6 to pypi. this version doesn't try to download the amalgamation by default.

@yurivict apologies for taking so long! :(

**Comment by yurivict** [comment]
No problem, thank you!
