### ISSUE TITLE
How to build in windows?

### ISSUE THREAD

**Issue by jbpineiro** [leapcode/pysqlcipher#23]
I try to build on windows with VS2013 compiler for Visual C++ and got it:
build\lib.win-amd64-2.7\pysqlcipher\_sqlite.pyd : fatal error LNK1120: 55 unresolved externals

**Comment by meskio** [comment]
Are you passing the `OPENSSL_CONF` variable with the path to the openssl lib?

**Comment by jbpineiro** [comment]
Nop, my fault.
Well, I compile the sqlite3.c to a dll file [sqlite3.dll] with MinGW. Can modify setup.py to use this dll instead of compile sqlite3.c?

**Comment by jbpineiro** [comment]
I try build again an got it:
=====================================================================
E:\Tesis\code\windows\env\pysqlcipher-develop>python setup.py build_sqlcipher
running build_sqlcipher
building 'pysqlcipher._sqlite' extension
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/module.c /Fobuild\temp.win-amd64-2.7\Release\src/module.obj
module.c
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/connection.c /Fobuild\temp.win-amd64-2.7\Release\src/connection.obj
connection.c
src/connection.c(600) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/cursor.c /Fobuild\temp.win-amd64-2.7\Release\src/cursor.obj
cursor.c
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/cache.c /Fobuild\temp.win-amd64-2.7\Release\src/cache.obj
cache.c
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/microprotocols.c /Fobuild\temp.win-amd64-2.7\Release\src/microprotocols.obj
microprotocols.c
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/prepare_protocol.c /Fobuild\temp.win-amd64-2.7\Release\src/prepare_protocol.obj
prepare_protocol.c
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/statement.c /Fobuild\temp.win-amd64-2.7\Release\src/statement.obj
statement.c
src/statement.c(180) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'int', possible loss of data
src/statement.c(227) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
src/statement.c(229) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
src/statement.c(231) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/util.c /Fobuild\temp.win-amd64-2.7\Release\src/util.obj
util.c
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -IC:\Python27\include -IC:\Python27\PC /Tcsrc/row.c /Fobuild\temp.win-amd64-2.7\Release\src/row.obj
row.c
src/row.c(92) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
src/row.c(150) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild\amd64 /EXPORT:init_sqlite build\temp.win-amd64-2.7\Release\src/module.obj build\temp.win-amd64-2.7\Release\src/connection.obj build\temp.win-amd64-2.7\Release\src/cursor.obj build\temp.win-amd64-2.7\Release\src/cache.obj build\temp.win-amd64-2.7\Release\src/microprotocols.obj build\temp.win-amd64-2.7\Release\src/prepare_protocol.obj build\temp.win-amd64-2.7\Release\src/statement.obj build\temp.win-amd64-2.7\Release\src/util.obj build\temp.win-amd64-2.7\Release\src/row.obj /OUT:build\lib.win-amd64-2.7\pysqlcipher\_sqlite.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\src\_sqlite.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\src\_sqlite.pyd.manifest
module.obj : warning LNK4197: export 'init_sqlite' specified multiple times; using first specification
   Creating library build\temp.win-amd64-2.7\Release\src\_sqlite.lib and object build\temp.win-amd64-2.7\Release\src\_sqlite.exp
module.obj : error LNK2019: unresolved external symbol sqlite3_libversion referenced in function init_sqlite
module.obj : error LNK2019: unresolved external symbol sqlite3_complete referenced in function module_connect
module.obj : error LNK2019: unresolved external symbol sqlite3_enable_shared_cache referenced in function module_connect
connection.obj : error LNK2019: unresolved external symbol sqlite3_close referenced in function pysqlite_connection_dealloc
connection.obj : error LNK2019: unresolved external symbol sqlite3_total_changes referenced in function _progress_handler
connection.obj : error LNK2019: unresolved external symbol sqlite3_interrupt referenced in function pysqlite_collation_callback
connection.obj : error LNK2019: unresolved external symbol sqlite3_busy_timeout referenced in function _pysqlite_connection_begin
connection.obj : error LNK2019: unresolved external symbol sqlite3_set_authorizer referenced in function _progress_handler
connection.obj : error LNK2019: unresolved external symbol sqlite3_progress_handler referenced in function _progress_handler
connection.obj : error LNK2019: unresolved external symbol sqlite3_open referenced in function _pysqlite_connection_begin
connection.obj : error LNK2019: unresolved external symbol sqlite3_prepare referenced in function _pysqlite_connection_begin
cursor.obj : error LNK2001: unresolved external symbol sqlite3_prepare
statement.obj : error LNK2001: unresolved external symbol sqlite3_prepare
connection.obj : error LNK2019: unresolved external symbol sqlite3_finalize referenced in function _pysqlite_connection_begin
cursor.obj : error LNK2001: unresolved external symbol sqlite3_finalize
statement.obj : error LNK2001: unresolved external symbol sqlite3_finalize
connection.obj : error LNK2019: unresolved external symbol sqlite3_create_function referenced in function _pysqlite_drop_unused_statement_references
connection.obj : error LNK2019: unresolved external symbol sqlite3_value_blob referenced in function _pysqlite_build_py_params
connection.obj : error LNK2019: unresolved external symbol sqlite3_value_bytes referenced in function _pysqlite_build_py_params
connection.obj : error LNK2019: unresolved external symbol sqlite3_value_double referenced in function _pysqlite_build_py_params
connection.obj : error LNK2019: unresolved external symbol sqlite3_value_int64 referenced in function _pysqlite_build_py_params
connection.obj : error LNK2019: unresolved external symbol sqlite3_value_text referenced in function _pysqlite_build_py_params
connection.obj : error LNK2019: unresolved external symbol sqlite3_value_type referenced in function _pysqlite_build_py_params
connection.obj : error LNK2019: unresolved external symbol sqlite3_aggregate_context referenced in function _pysqlite_step_callback
connection.obj : error LNK2019: unresolved external symbol sqlite3_user_data referenced in function _pysqlite_func_callback
connection.obj : error LNK2019: unresolved external symbol sqlite3_result_blob referenced in function _pysqlite_set_result
connection.obj : error LNK2019: unresolved external symbol sqlite3_result_double referenced in function _pysqlite_set_result
connection.obj : error LNK2019: unresolved external symbol sqlite3_result_error referenced in function _sqlite3_result_error
connection.obj : error LNK2019: unresolved external symbol sqlite3_result_int64 referenced in function _pysqlite_set_result
connection.obj : error LNK2019: unresolved external symbol sqlite3_result_null referenced in function _pysqlite_set_result
connection.obj : error LNK2019: unresolved external symbol sqlite3_result_text referenced in function _pysqlite_set_result
connection.obj : error LNK2019: unresolved external symbol sqlite3_create_collation referenced in function pysqlite_collation_callback
connection.obj : error LNK2019: unresolved external symbol sqlite3_load_extension referenced in function _progress_handler
connection.obj : error LNK2019: unresolved external symbol sqlite3_enable_load_extension referenced in function _progress_handler
cursor.obj : error LNK2019: unresolved external symbol sqlite3_last_insert_rowid referenced in function _pysqlite_query_execute
cursor.obj : error LNK2019: unresolved external symbol sqlite3_changes referenced in function _pysqlite_query_execute
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_count referenced in function pysqlite_build_row_cast_map
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_name referenced in function pysqlite_build_row_cast_map
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_decltype referenced in function pysqlite_build_row_cast_map
cursor.obj : error LNK2019: unresolved external symbol sqlite3_data_count referenced in function _pysqlite_fetch_one_row
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_blob referenced in function _pysqlite_fetch_one_row
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_bytes referenced in function _pysqlite_fetch_one_row
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_double referenced in function _pysqlite_fetch_one_row
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_int64 referenced in function _pysqlite_fetch_one_row
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_text referenced in function _pysqlite_fetch_one_row
cursor.obj : error LNK2019: unresolved external symbol sqlite3_column_type referenced in function _pysqlite_fetch_one_row
cursor.obj : error LNK2019: unresolved external symbol sqlite3_get_autocommit referenced in function _pysqlite_query_execute
statement.obj : error LNK2019: unresolved external symbol sqlite3_bind_blob referenced in function pysqlite_statement_bind_parameter
statement.obj : error LNK2019: unresolved external symbol sqlite3_bind_double referenced in function pysqlite_statement_bind_parameter
statement.obj : error LNK2019: unresolved external symbol sqlite3_bind_int64 referenced in function pysqlite_statement_bind_parameter
statement.obj : error LNK2019: unresolved external symbol sqlite3_bind_null referenced in function pysqlite_statement_bind_parameter
statement.obj : error LNK2019: unresolved external symbol sqlite3_bind_text referenced in function pysqlite_statement_bind_parameter
statement.obj : error LNK2019: unresolved external symbol sqlite3_bind_parameter_count referenced in function pysqlite_statement_bind_parameters
statement.obj : error LNK2019: unresolved external symbol sqlite3_bind_parameter_name referenced in function pysqlite_statement_bind_parameters
statement.obj : error LNK2019: unresolved external symbol sqlite3_reset referenced in function pysqlite_statement_reset
util.obj : error LNK2001: unresolved external symbol sqlite3_reset
statement.obj : error LNK2019: unresolved external symbol sqlite3_transfer_bindings referenced in function pysqlite_statement_recompile
util.obj : error LNK2019: unresolved external symbol sqlite3_errcode referenced in function _pysqlite_seterror
util.obj : error LNK2019: unresolved external symbol sqlite3_errmsg referenced in function _pysqlite_seterror
util.obj : error LNK2019: unresolved external symbol sqlite3_step referenced in function pysqlite_step
build\lib.win-amd64-2.7\pysqlcipher\_sqlite.pyd : fatal error LNK1120: 55 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\BIN\\amd64\\link.exe' failed with exit status 1120

**Comment by meskio** [comment]
this errors look weird. Can it be that you are trying to compile against sqlite instead of sqlcypher?

If I remember correctly pysqlcypher downloads the sqlcypher code in the setup process. I got some errors doing that in windows myself and I end up puting the tgz by hand in place. I can check my notes how I did that.

**Comment by jbpineiro** [comment]
Search between the notes and tell me how you did it.
For the moment I did that:
1. Download manually amalgamation-sqlcipher-2.1.0.zip and put the content [sqlite3.c, sqlite3.h] in the amalgamation folder into pysqlcipher directory.
2. Download, configure, compile and install the openssl-1.0.2f.tar.gz, all OK.
3. Download and install VCForPython27.msi.
4. Run the following script:
set LIB=%LIB%;C:\openssl\lib
set INCLUDE=%INCLUDE%;C:\openssl\include
set LIBPATH=%LIBPATH%;C:\openssl\lib
set OPENSSL_CONF=C:\openssl\ssl
python setup.py build_ext

I got the following output:
*********************************
running build_ext
building 'pysqlcipher._sqlite' extension
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/module.c /Fobuild\temp.win-amd64-2.7\Release\src/module.obj
module.c
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/connection.c /Fobuild\temp.win-amd64-2.7\Release\src/connection.obj
connection.c
src/connection.c(600) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/cursor.c /Fobuild\temp.win-amd64-2.7\Release\src/cursor.obj
cursor.c
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/cache.c /Fobuild\temp.win-amd64-2.7\Release\src/cache.obj
cache.c
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/microprotocols.c /Fobuild\temp.win-amd64-2.7\Release\src/microprotocols.obj
microprotocols.c
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/prepare_protocol.c /Fobuild\temp.win-amd64-2.7\Release\src/prepare_protocol.obj
prepare_protocol.c
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/statement.c /Fobuild\temp.win-amd64-2.7\Release\src/statement.obj
statement.c
src/statement.c(180) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'int', possible loss of data
src/statement.c(227) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
src/statement.c(229) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
src/statement.c(231) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/util.c /Fobuild\temp.win-amd64-2.7\Release\src/util.obj
util.c
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcsrc/row.c /Fobuild\temp.win-amd64-2.7\Release\src/row.obj
row.c
src/row.c(92) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
src/row.c(150) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DMODULE_NAME=\"pysqlcipher.dbapi2\" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Dinline=__inline -Iamalgamation -Ic:\python27\include -IE:\Projects\virtualenv\sqlprotect\PC /Tcamalgamation\sqlite3.c /Fobuild\temp.win-amd64-2.7\Release\amalgamation\sqlite3.obj
sqlite3.c
amalgamation\sqlite3.c(13563) : warning C4018: '<=' : signed/unsigned mismatch
C:\Users\geek\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\python27\Libs /LIBPATH:E:\Projects\virtualenv\sqlprotect\libs /LIBPATH:E:\Projects\virtualenv\sqlprotect\PCbuild\amd64 /EXPORT:init_sqlite build\temp.win-amd64-2.7\Release\src/module.obj build\temp.win-amd64-2.7\Release\src/connection.obj build\temp.win-amd64-2.7\Release\src/cursor.obj build\temp.win-amd64-2.7\Release\src/cache.obj build\temp.win-amd64-2.7\Release\src/microprotocols.obj build\temp.win-amd64-2.7\Release\src/prepare_protocol.obj build\temp.win-amd64-2.7\Release\src/statement.obj build\temp.win-amd64-2.7\Release\src/util.obj build\temp.win-amd64-2.7\Release\src/row.obj build\temp.win-amd64-2.7\Release\amalgamation\sqlite3.obj /OUT:build\lib.win-amd64-2.7\pysqlcipher\_sqlite.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\src\_sqlite.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\src\_sqlite.pyd.manifest libeay32.lib ssleay32.lib
module.obj : warning LNK4197: export 'init_sqlite' specified multiple times; using first specification
   Creating library build\temp.win-amd64-2.7\Release\src\_sqlite.lib and object build\temp.win-amd64-2.7\Release\src\_sqlite.exp
sqlite3.obj : error LNK2019: unresolved external symbol RAND_bytes referenced in function sqlcipher_random
sqlite3.obj : error LNK2019: unresolved external symbol OBJ_nid2sn referenced in function sqlcipher_codec_ctx_get_cipher
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CIPHER_nid referenced in function sqlcipher_codec_ctx_get_cipher
sqlite3.obj : error LNK2019: unresolved external symbol OPENSSL_add_all_algorithms_noconf referenced in function sqlcipher_activate
sqlite3.obj : error LNK2019: unresolved external symbol EVP_get_cipherbyname referenced in function sqlcipher_activate
sqlite3.obj : error LNK2019: unresolved external symbol EVP_cleanup referenced in function sqlcipher_deactivate
sqlite3.obj : error LNK2019: unresolved external symbol HMAC_CTX_cleanup referenced in function sqlcipher_page_hmac
sqlite3.obj : error LNK2019: unresolved external symbol HMAC_Final referenced in function sqlcipher_page_hmac
sqlite3.obj : error LNK2019: unresolved external symbol HMAC_Update referenced in function sqlcipher_page_hmac
sqlite3.obj : error LNK2019: unresolved external symbol HMAC_Init_ex referenced in function sqlcipher_page_hmac
sqlite3.obj : error LNK2019: unresolved external symbol EVP_sha1 referenced in function sqlcipher_page_hmac
sqlite3.obj : error LNK2019: unresolved external symbol HMAC_CTX_init referenced in function sqlcipher_page_hmac
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CIPHER_CTX_cleanup referenced in function sqlcipher_page_cipher
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CipherFinal referenced in function sqlcipher_page_cipher
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CipherUpdate referenced in function sqlcipher_page_cipher
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CIPHER_CTX_set_padding referenced in function sqlcipher_page_cipher
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CipherInit referenced in function sqlcipher_page_cipher
sqlite3.obj : error LNK2019: unresolved external symbol PKCS5_PBKDF2_HMAC_SHA1 referenced in function sqlcipher_cipher_ctx_key_derive
sqlite3.obj : error LNK2019: unresolved external symbol EVP_MD_size referenced in function sqlcipher_codec_ctx_set_cipher
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CIPHER_block_size referenced in function sqlcipher_codec_ctx_set_cipher
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CIPHER_iv_length referenced in function sqlcipher_codec_ctx_set_cipher
sqlite3.obj : error LNK2019: unresolved external symbol EVP_CIPHER_key_length referenced in function sqlcipher_codec_ctx_set_cipher
build\lib.win-amd64-2.7\pysqlcipher\_sqlite.pyd : fatal error LNK1120: 22 unresolved externals
error: command 'C:\\Users\\geek\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120

**Comment by jbpineiro** [comment]
Finally after many search on internet and intents I can install pysqlcipher.The errors: [opensslx32 vs pythonx64]
------------------------------------------
But when I run the program i got:
-----------------------------------------
Traceback (most recent call last):
  File "E:/Tesis/code/tags/db-protect/sqlprotect/sqlprotect.py", line 2, in <module>
    from pysqlcipher import dbapi2 as sqlcipher
  File "build\bdist.win-amd64\egg\pysqlcipher\dbapi2.py", line 31, in <module>
  File "build\bdist.win-amd64\egg\pysqlcipher\_sqlite.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\pysqlcipher\_sqlite.py", line 6, in __bootstrap__
ImportError: DLL load failed: The specified module could not be found.

---------------------------
What it means?, not again.....

**Comment by jbpineiro** [comment]
Problem solved!!!
I use the http://www.dependencywalker.com/ to inspect _sqlite.pyd, I found missing DLLs dependences (LIBEAY32.DLL, MSVCR90.DLL) . Add its to C:\Windows\System32 and problem solved.
Thanks to pysqlcipher team!!!

**Comment by meskio** [comment]
Thank you @jbpineiro for all the complete report, you solved it yourself and give us a lot of info for the next time we come around this kind of issues.

I'm happy to see it's working for you.

**Comment by Iria-D** [comment]
how the hell to build this on windows 11. I am already busy 2 full days
python installed, pip included, installed with zip all same 

LINK : warning LNK4044: unrecognized option '/lsqlcipher'; ignored
LINK : fatal error LNK1181: cannot open input file 'sqlcipher.lib'
