### ISSUE TITLE
Amalgamation site is down - Not working with pip

### ISSUE THREAD

**Issue by abhaybhargav** [leapcode/pysqlcipher#28]
this url: [](https://downloads.leap.se/libs/pysqlcipher/amalgamation-sqlcipher-2.1.0.zip) for the amalgamation download is down, causing pip installs to fail

![image](https://cloud.githubusercontent.com/assets/4427607/18981317/be99cd84-86fa-11e6-9aa8-85e9ecd9ed79.png)

**Comment by mdomke** [comment]
Wouldn't it be better to vendor the dependencies into the package instead of downloading somewhere from the internet?

**Comment by SirScott** [comment]
Additionally, if building against the system libraries (`python setup.py build_sqlcipher`), then attempting to install via `python setup.py install` still winds up triggering build_ext, which in turn uses https://github.com/leapcode/pysqlcipher/blob/develop/setup.py#L159, resulting in an unecessary attempt to fetch (a now down) amalgamation url.

**Comment by kalikaneko** [comment]
apologies, the server that holds the amalgamation is down due to an outage. service will be resumed soon.

> Wouldn't it be better to vendor the dependencies into the package

we want to make the bundling optional and disabled by default. building against system lib should be preferred.
you can also build the amalgamation from upstream sqlcipher and put it on a folder. 

> Additionally, if building against the system libraries (python setup.py build_sqlcipher), then attempting to install via python setup.py install still winds up 

> attempting to install via python setup.py install still winds up triggering build_ext

looks like a bug

**Comment by kalikaneko** [comment]
I will push a new version shortly, vendoring the bundle and making compilation about the system lib the default. some testing will be appreciated before pushing to pypi.

**Comment by kalikaneko** [comment]
with commit 3fd5e3d5e9785 this should be solved.
* it vendors the amalgamation
* it builds against system-wide libsqlcipher by default
* it allows to build against bundled sqlcipher, using --bundled
* it allows to pass a path to a different amalgamation

Some testing would be greatly appreciated. I will push a new version to pypi in some minutes doing these changes.

**Comment by kalikaneko** [comment]
@SirScott do you mind testing installation from master at 3fd5e3d ?

**Comment by kalikaneko** [comment]
I have pushed version 2.6.6 to pypi. this version doesn't try to download the amalgamation by default.

**Comment by SirScott** [comment]
@kalikaneko: That worked for me, thank you!
