### ISSUE TITLE
How to use pysqlcipher with SQLalchemy?

### ISSUE THREAD

**Issue by dionyziz** [leapcode/pysqlcipher#7]
Is it possible to use pysqlcipher with SQLalchemy?

**Comment by kalikaneko** [comment]
According to the docs, pysqlcipher is supported from version 0.9.9 of sqalchemy: http://docs.sqlalchemy.org/en/rel_0_9/dialects/sqlite.html#module-sqlalchemy.dialects.sqlite.pysqlcipher
